#! /bin/sh

# Run Polybar
polybar mainbar-bspwm &
echo "Polybar done"

# Start SXHKD
sxhkd &
echo "sxhkd done"

# Start Picom
picom &
echo "picom done"

# Select wallpaper
nitrogen --restore
#feh --bg-fill /home/charl/Pictures/Wallpapers/blue-wolf-66vm01n7e60ewa7l.jpeg &
echo "selecting wallpaper done"



#Set Keyboard Layout
setxkbmap -layout uk &
echo "keyboard done"

# bspc things


#Monitor Config
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width			4
bspc config window_gap				6

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#216691"
bspc config normal_border_color		"#4f7091"
bspc config active_border_color		"#4aaad6"
bspc config presel_feedback_color	"#50FA7B"
echo "bspc things done"

# All startup things
dunst &
xsetroot -cursor_name left_ptr &
#xrdb -merge $HOME/.Xresources &
#xset r rate 200 50 &
echo "This is the end of bspwmrc"

